### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by raelb** [aehimself/AEFramework#1]
> AEFramework is a set of helper units / components which I use for most of my projects. Since they might be of interest of others it is **not** hosted on GitHub.

Shouldn't that be "it is hosted on GitHub."?

**Comment by aehimself** [comment]
Thanks, it is indeed hosted on GitHub :)

**Comment by raelb** [comment]
> Since they might be of interest **to** others

While I'm at it... :)
