### ISSUE TITLE
demo updater

### ISSUE THREAD

**Issue by Marijsoft** [aehimself/AEFramework#2]
Hello mate, can you post a demo updater i don't understand how to create file updater for update the app. thx u

**Comment by aehimself** [comment]
Guilty as charged, I must write some proper documentation about my stuff. For the time being you can check the initial post [here](https://en.delphipraxis.net/topic/6713-update-framework-question/?do=findComment&comment=58049).
Basically, create a TAEUpdaterUpdateFile instance, add a product, a product file and a file version. Save the instance to a TFileStream or TMemoryStream and place it on your webserver.

Let me know if this was enough to get you started or I should explain more :)

**Comment by Marijsoft** [comment]
thx u for documentation i created the json file with your instruction
